# Generated by Django 4.1 on 2022-09-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('categoria', models.CharField(max_length=20)),
                ('texto', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=20)),
                ('ingredientes', models.CharField(max_length=500)),
                ('procedimiento', models.CharField(max_length=5000)),
            ],
        ),
    ]
