# Generated by Django 4.1 on 2022-09-19 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
